export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART';
export const REMOVE_FROM_SHOPPING_CART = 'REMOVE_FROM_SHOPPING_CART';

export const INCREMENT_PRODUCT_QTY = 'INCREMENT_PRODUCT_QTY';
export const DECREMENT_PRODUCT_QTY = 'DECREMENT_PRODUCT_QTY';

export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const UNSET_SELECTED_PRODUCT = 'UNSET_SELECTED_PRODUCT';
